"""Added likes and likes functionality

Revision ID: 545c4efc5706
Revises: 9fb60dd15f34
Create Date: 2024-05-18 23:46:41.099150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545c4efc5706'
down_revision = '9fb60dd15f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
